/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package integrador.telas;

import integrador.dao.ProdutosDAO;
import integrador.dao.TipoDeProdutosDAO;
import integrador.model.Produtos;
import integrador.model.TipoDeProduto;
import javax.swing.JOptionPane;
import integrador.utilitarios.Utilitarios;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form funcionarios
     */
    
    public void listar(){
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.Listar();
        DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
        dados.setNumRows(0);
        for(Produtos p : lista){
            dados.addRow(new Object[]{
                p.getIdProduct(),
                p.getNameProduct(),
                p.getPrice(),
                p.getStock(),
                p.getTipodeproduto().getProductType()
            });
        }
    }
    
    public CadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelGuiasMenuControle1 = new javax.swing.JTabbedPane();
        CadastrarProdutos1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        idProduto1 = new javax.swing.JTextField();
        txtDescricao1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botaoSalvar1 = new javax.swing.JButton();
        btnPesquisar1 = new javax.swing.JButton();
        botaoNovo1 = new javax.swing.JButton();
        botaoEditar1 = new javax.swing.JButton();
        botaoExcluir1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtPreco1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtQuantidade1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbTipoProduto1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        PainelControleEstoque1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PainelGuiasMenuControle2 = new javax.swing.JTabbedPane();
        CadastrarProdutos2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        idProduto2 = new javax.swing.JTextField();
        txtDescricao2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botaoSalvar2 = new javax.swing.JButton();
        btnPesquisar2 = new javax.swing.JButton();
        botaoNovo2 = new javax.swing.JButton();
        botaoEditar2 = new javax.swing.JButton();
        botaoExcluir2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtPreco2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtQuantidade2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbTipoProduto2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();
        PainelControleEstoque2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        PainelControleEstoque = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelGuiasMenuControle = new javax.swing.JTabbedPane();
        CadastrarProdutos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idProduto = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botaoSalvar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        botaoNovo = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbTipoProduto = new javax.swing.JComboBox();
        ConsultarProdutos = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtPesquisaDescricao = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        PainelGuiasMenuControle1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CadastrarProdutos1.setBackground(new java.awt.Color(204, 204, 204));
        CadastrarProdutos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CadastrarProdutos1.setPreferredSize(new java.awt.Dimension(1100, 700));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Codigo:");

        idProduto1.setEditable(false);
        idProduto1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idProduto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        idProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProduto1ActionPerformed(evt);
            }
        });

        txtDescricao1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescricao1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtDescricao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricao1ActionPerformed(evt);
            }
        });
        txtDescricao1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricao1KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Preço:");

        botaoSalvar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone salvar.png"))); // NOI18N
        botaoSalvar1.setText("Salvar");
        botaoSalvar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvar1ActionPerformed(evt);
            }
        });

        btnPesquisar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone pesquisar.png"))); // NOI18N
        btnPesquisar1.setText("Pesquisar");
        btnPesquisar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar1ActionPerformed(evt);
            }
        });

        botaoNovo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone novo.png"))); // NOI18N
        botaoNovo1.setText("Novo");
        botaoNovo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovo1ActionPerformed(evt);
            }
        });

        botaoEditar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone editar.png"))); // NOI18N
        botaoEditar1.setText("Editar");
        botaoEditar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar1ActionPerformed(evt);
            }
        });

        botaoExcluir1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone excluir.png"))); // NOI18N
        botaoExcluir1.setText("Excluir");
        botaoExcluir1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluir1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Descrição:");

        txtPreco1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPreco1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtPreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreco1ActionPerformed(evt);
            }
        });
        txtPreco1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPreco1KeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Qtd. Estoque");

        txtQuantidade1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuantidade1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtQuantidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidade1ActionPerformed(evt);
            }
        });
        txtQuantidade1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidade1KeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Produto tipo:");

        cbTipoProduto1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbTipoProduto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cbTipoProduto1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbTipoProduto1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbTipoProduto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoProduto1MouseClicked(evt);
            }
        });
        cbTipoProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoProduto1ActionPerformed(evt);
            }
        });

        tabela1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tabela1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição:", "Preço", "Estoque", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(222, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout CadastrarProdutos1Layout = new javax.swing.GroupLayout(CadastrarProdutos1);
        CadastrarProdutos1.setLayout(CadastrarProdutos1Layout);
        CadastrarProdutos1Layout.setHorizontalGroup(
            CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarProdutos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastrarProdutos1Layout.createSequentialGroup()
                        .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadastrarProdutos1Layout.createSequentialGroup()
                                .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CadastrarProdutos1Layout.createSequentialGroup()
                                        .addComponent(botaoNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPreco1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQuantidade1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CadastrarProdutos1Layout.setVerticalGroup(
            CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarProdutos1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar1))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastrarProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar1)
                    .addComponent(botaoNovo1)
                    .addComponent(botaoEditar1)
                    .addComponent(botaoExcluir1))
                .addContainerGap())
        );

        PainelGuiasMenuControle1.addTab("Cadastrar Produtos", CadastrarProdutos1);

        PainelControleEstoque1.setBackground(new java.awt.Color(0, 0, 0));
        PainelControleEstoque1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("MonoLisa-BoldItalic", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(207, 181, 59));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Estoque");

        javax.swing.GroupLayout PainelControleEstoque1Layout = new javax.swing.GroupLayout(PainelControleEstoque1);
        PainelControleEstoque1.setLayout(PainelControleEstoque1Layout);
        PainelControleEstoque1Layout.setHorizontalGroup(
            PainelControleEstoque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelControleEstoque1Layout.setVerticalGroup(
            PainelControleEstoque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelControleEstoque1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PainelGuiasMenuControle2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        CadastrarProdutos2.setBackground(new java.awt.Color(204, 204, 204));
        CadastrarProdutos2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CadastrarProdutos2.setPreferredSize(new java.awt.Dimension(1100, 700));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Codigo:");

        idProduto2.setEditable(false);
        idProduto2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idProduto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        idProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProduto2ActionPerformed(evt);
            }
        });

        txtDescricao2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescricao2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtDescricao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricao2ActionPerformed(evt);
            }
        });
        txtDescricao2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricao2KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Preço:");

        botaoSalvar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoSalvar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone salvar.png"))); // NOI18N
        botaoSalvar2.setText("Salvar");
        botaoSalvar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvar2ActionPerformed(evt);
            }
        });

        btnPesquisar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPesquisar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone pesquisar.png"))); // NOI18N
        btnPesquisar2.setText("Pesquisar");
        btnPesquisar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar2ActionPerformed(evt);
            }
        });

        botaoNovo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoNovo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone novo.png"))); // NOI18N
        botaoNovo2.setText("Novo");
        botaoNovo2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoNovo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovo2ActionPerformed(evt);
            }
        });

        botaoEditar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoEditar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone editar.png"))); // NOI18N
        botaoEditar2.setText("Editar");
        botaoEditar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar2ActionPerformed(evt);
            }
        });

        botaoExcluir2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botaoExcluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone excluir.png"))); // NOI18N
        botaoExcluir2.setText("Excluir");
        botaoExcluir2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        botaoExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluir2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Descrição:");

        txtPreco2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPreco2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtPreco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreco2ActionPerformed(evt);
            }
        });
        txtPreco2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPreco2KeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Qtd. Estoque");

        txtQuantidade2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuantidade2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtQuantidade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidade2ActionPerformed(evt);
            }
        });
        txtQuantidade2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidade2KeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Produto tipo:");

        cbTipoProduto2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbTipoProduto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cbTipoProduto2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbTipoProduto2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbTipoProduto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoProduto2MouseClicked(evt);
            }
        });
        cbTipoProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoProduto2ActionPerformed(evt);
            }
        });

        tabela2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tabela2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição:", "Preço", "Estoque", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabela2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(222, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout CadastrarProdutos2Layout = new javax.swing.GroupLayout(CadastrarProdutos2);
        CadastrarProdutos2.setLayout(CadastrarProdutos2Layout);
        CadastrarProdutos2Layout.setHorizontalGroup(
            CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarProdutos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastrarProdutos2Layout.createSequentialGroup()
                        .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadastrarProdutos2Layout.createSequentialGroup()
                                .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CadastrarProdutos2Layout.createSequentialGroup()
                                        .addComponent(botaoNovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoSalvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoExcluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPreco2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQuantidade2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CadastrarProdutos2Layout.setVerticalGroup(
            CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarProdutos2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(idProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar2))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastrarProdutos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar2)
                    .addComponent(botaoNovo2)
                    .addComponent(botaoEditar2)
                    .addComponent(botaoExcluir2))
                .addContainerGap())
        );

        PainelGuiasMenuControle2.addTab("Cadastrar Produtos", CadastrarProdutos2);

        PainelControleEstoque2.setBackground(new java.awt.Color(0, 0, 0));
        PainelControleEstoque2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("MonoLisa-BoldItalic", 1, 32)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(207, 181, 59));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Estoque");

        javax.swing.GroupLayout PainelControleEstoque2Layout = new javax.swing.GroupLayout(PainelControleEstoque2);
        PainelControleEstoque2.setLayout(PainelControleEstoque2Layout);
        PainelControleEstoque2Layout.setHorizontalGroup(
            PainelControleEstoque2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelControleEstoque2Layout.setVerticalGroup(
            PainelControleEstoque2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelControleEstoque2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PainelControleEstoque.setBackground(new java.awt.Color(60, 110, 113));
        PainelControleEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("MonoLisa-BoldItalic", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout PainelControleEstoqueLayout = new javax.swing.GroupLayout(PainelControleEstoque);
        PainelControleEstoque.setLayout(PainelControleEstoqueLayout);
        PainelControleEstoqueLayout.setHorizontalGroup(
            PainelControleEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelControleEstoqueLayout.setVerticalGroup(
            PainelControleEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelControleEstoqueLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PainelGuiasMenuControle.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N

        CadastrarProdutos.setBackground(new java.awt.Color(40, 75, 99));
        CadastrarProdutos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CadastrarProdutos.setPreferredSize(new java.awt.Dimension(1100, 700));

        jLabel2.setBackground(new java.awt.Color(217, 217, 217));
        jLabel2.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(217, 217, 217));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Codigo:");

        idProduto.setEditable(false);
        idProduto.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        idProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        idProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProdutoActionPerformed(evt);
            }
        });

        txtDescricao.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        txtDescricao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(217, 217, 217));
        jLabel3.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(217, 217, 217));
        jLabel3.setText("Preço:");

        botaoSalvar.setFont(new java.awt.Font("MonoLisa-Bold", 0, 14)); // NOI18N
        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone salvar.png"))); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("MonoLisa-Bold", 0, 14)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone pesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        botaoNovo.setFont(new java.awt.Font("MonoLisa-Bold", 0, 14)); // NOI18N
        botaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone novo.png"))); // NOI18N
        botaoNovo.setText("Novo");
        botaoNovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        botaoEditar.setFont(new java.awt.Font("MonoLisa-Bold", 0, 14)); // NOI18N
        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone editar.png"))); // NOI18N
        botaoEditar.setText("Editar");
        botaoEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoExcluir.setFont(new java.awt.Font("MonoLisa-Bold", 0, 14)); // NOI18N
        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone excluir.png"))); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(217, 217, 217));
        jLabel9.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(217, 217, 217));
        jLabel9.setText("Descrição:");

        txtPreco.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        txtPreco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        txtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecoKeyPressed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(217, 217, 217));
        jLabel10.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(217, 217, 217));
        jLabel10.setText("Qtd. Estoque");

        txtQuantidade.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        txtQuantidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(217, 217, 217));
        jLabel12.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(217, 217, 217));
        jLabel12.setText("Produto tipo:");

        cbTipoProduto.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        cbTipoProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cbTipoProduto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbTipoProdutoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbTipoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoProdutoMouseClicked(evt);
            }
        });
        cbTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastrarProdutosLayout = new javax.swing.GroupLayout(CadastrarProdutos);
        CadastrarProdutos.setLayout(CadastrarProdutosLayout);
        CadastrarProdutosLayout.setHorizontalGroup(
            CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                        .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                                .addComponent(botaoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        CadastrarProdutosLayout.setVerticalGroup(
            CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarProdutosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(CadastrarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoNovo)
                    .addComponent(botaoEditar)
                    .addComponent(botaoExcluir))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        PainelGuiasMenuControle.addTab("Cadastrar Produtos", CadastrarProdutos);

        ConsultarProdutos.setBackground(new java.awt.Color(40, 75, 99));

        jLabel11.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(217, 217, 217));
        jLabel11.setText("Descrição do Produto:");

        txtPesquisaDescricao.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        txtPesquisaDescricao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPesquisaDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaDescricaoActionPerformed(evt);
            }
        });
        txtPesquisaDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaDescricaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaDescricaoKeyReleased(evt);
            }
        });

        btnPesquisa.setFont(new java.awt.Font("MonoLisa-Regular", 0, 14)); // NOI18N
        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone pesquisar.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        tabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tabela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição:", "Preço", "Estoque", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setHeaderValue("ID");
            tabela.getColumnModel().getColumn(1).setHeaderValue("Descrição:");
            tabela.getColumnModel().getColumn(2).setHeaderValue("Preço");
            tabela.getColumnModel().getColumn(3).setHeaderValue("Estoque");
            tabela.getColumnModel().getColumn(4).setHeaderValue("Tipo");
        }

        javax.swing.GroupLayout ConsultarProdutosLayout = new javax.swing.GroupLayout(ConsultarProdutos);
        ConsultarProdutos.setLayout(ConsultarProdutosLayout);
        ConsultarProdutosLayout.setHorizontalGroup(
            ConsultarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisaDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        ConsultarProdutosLayout.setVerticalGroup(
            ConsultarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultarProdutosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ConsultarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PainelGuiasMenuControle.addTab("Consulta de Produtos", ConsultarProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelControleEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelGuiasMenuControle, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelControleEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PainelGuiasMenuControle, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Produtos obj = new Produtos();
        obj.setNameProduct(txtDescricao.getText());
        obj.setPrice(Double.valueOf(txtPreco.getText()));
        obj.setStock(Integer.valueOf(txtQuantidade.getText()));
        obj.setTipodeproduto((TipoDeProduto)cbTipoProduto.getSelectedItem());
        
        ProdutosDAO dao = new ProdutosDAO();
        dao.Salvar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        
        String nameProduct = txtDescricao.getText();
        
        Produtos obj = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();
        
        TipoDeProduto tp = new TipoDeProduto();
        TipoDeProdutosDAO tpdao = new TipoDeProdutosDAO();
        
        
        obj = dao.BuscarProdutos(nameProduct);
        
        if(obj.getNameProduct() != null){
            
            idProduto.setText(String.valueOf(obj.getIdProduct()));
            txtDescricao.setText(obj.getNameProduct());
            txtPreco.setText(String.valueOf(obj.getPrice()));
            txtQuantidade.setText(String.valueOf(obj.getStock()));
        
            tp = tpdao.BuscarTipoDeProdutos(obj.getTipodeproduto().getProductType());
            cbTipoProduto.getModel().setSelectedItem(tp);
            
        }else{
            JOptionPane.showMessageDialog(null, "Produto nao encontrado");
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        
        
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        Produtos obj = new Produtos();
        obj.setIdProduct(Integer.valueOf(idProduto.getText()));
        obj.setNameProduct(txtDescricao.getText());
        obj.setPrice(Double.valueOf(txtPreco.getText()));
        obj.setStock(Integer.valueOf(txtQuantidade.getText()));
        
        TipoDeProduto tp = new TipoDeProduto();
        tp = (TipoDeProduto) cbTipoProduto.getSelectedItem();
        
        obj.setTipodeproduto(tp);
        
        ProdutosDAO dao = new ProdutosDAO();
        dao.Editar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        Produtos obj = new Produtos();
        obj.setIdProduct(Integer.valueOf(idProduto.getText()));
        ProdutosDAO dao = new ProdutosDAO();
        dao.Excluir(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
        
        //esse utilitarios é pra colocar icone na janela no canto superior esquerdo
        Utilitarios u = new Utilitarios();
        u.InserirIcone(this);
    }//GEN-LAST:event_formWindowActivated

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        String nameProduct = "%" + txtPesquisaDescricao.getText() + "%";
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.Filtrar(nameProduct);
        DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
        dados.setNumRows(0);
        for(Produtos p : lista){
            dados.addRow(new Object[]{
                p.getIdProduct(),
                p.getNameProduct(),
                p.getPrice(),
                p.getStock(),
                p.getTipodeproduto().getProductType()
            });
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txtPesquisaDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaDescricaoActionPerformed

    private void txtPesquisaDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaDescricaoKeyReleased
        String nameProduct = "%" + txtPesquisaDescricao.getText() + "%";
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.Filtrar(nameProduct);
        DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
        dados.setNumRows(0);
        for(Produtos p : lista){
            dados.addRow(new Object[]{
                p.getIdProduct(),
                p.getNameProduct(),
                p.getPrice(),
                p.getStock(),
                p.getTipodeproduto().getProductType()
            });
        }
    }//GEN-LAST:event_txtPesquisaDescricaoKeyReleased

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String nameProduct = txtDescricao.getText();
        
        Produtos obj = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();
        
        TipoDeProduto tp = new TipoDeProduto();
        TipoDeProdutosDAO tpdao = new TipoDeProdutosDAO();
        
        
        obj = dao.BuscarProdutos(nameProduct);
        
        if(obj.getNameProduct() != null){
            
            idProduto.setText(String.valueOf(obj.getIdProduct()));
            txtDescricao.setText(obj.getNameProduct());
            txtPreco.setText(String.valueOf(obj.getPrice()));
            txtQuantidade.setText(String.valueOf(obj.getStock()));
        
            tp = tpdao.BuscarTipoDeProdutos(obj.getTipodeproduto().getProductType());
            cbTipoProduto.getModel().setSelectedItem(tp);
            }else{
            JOptionPane.showMessageDialog(null, "Produto nao encontrado");
        }
        }
    }//GEN-LAST:event_txtDescricaoKeyPressed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        PainelGuiasMenuControle.setSelectedIndex(0);
        idProduto.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        txtDescricao.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        txtPreco.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        txtQuantidade.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        
        TipoDeProduto tp = new TipoDeProduto();
        TipoDeProdutosDAO tpDAO = new TipoDeProdutosDAO();
        
        tp = tpDAO.BuscarTipoDeProdutos(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
        cbTipoProduto.removeAllItems();
        cbTipoProduto.getModel().setSelectedItem(tp);
    }//GEN-LAST:event_tabelaMouseClicked

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoKeyPressed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void idProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProdutoActionPerformed

    private void cbTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoProdutoActionPerformed

    private void cbTipoProdutoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbTipoProdutoAncestorAdded
        
    }//GEN-LAST:event_cbTipoProdutoAncestorAdded

    private void cbTipoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoProdutoMouseClicked
        TipoDeProdutosDAO dao = new TipoDeProdutosDAO();
        List<TipoDeProduto> lista = dao.Listar();
        cbTipoProduto.removeAllItems();
        for(TipoDeProduto tp : lista){
        cbTipoProduto.addItem(tp);        
        }
    }//GEN-LAST:event_cbTipoProdutoMouseClicked

    private void idProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProduto1ActionPerformed

    private void txtDescricao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricao1ActionPerformed

    private void txtDescricao1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricao1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String nameProduct = txtDescricao.getText();

            Produtos obj = new Produtos();
            ProdutosDAO dao = new ProdutosDAO();

            TipoDeProduto tp = new TipoDeProduto();
            TipoDeProdutosDAO tpdao = new TipoDeProdutosDAO();

            obj = dao.BuscarProdutos(nameProduct);

            if(obj.getNameProduct() != null){

                idProduto.setText(String.valueOf(obj.getIdProduct()));
                txtDescricao.setText(obj.getNameProduct());
                txtPreco.setText(String.valueOf(obj.getPrice()));
                txtQuantidade.setText(String.valueOf(obj.getStock()));

                tp = tpdao.BuscarTipoDeProdutos(obj.getTipodeproduto().getProductType());
                cbTipoProduto.getModel().setSelectedItem(tp);
            }else{
                JOptionPane.showMessageDialog(null, "Produto nao encontrado");
            }
        }
    }//GEN-LAST:event_txtDescricao1KeyPressed

    private void botaoSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvar1ActionPerformed
        Produtos obj = new Produtos();
        obj.setNameProduct(txtDescricao.getText());
        obj.setPrice(Double.valueOf(txtPreco.getText()));
        obj.setStock(Integer.valueOf(txtQuantidade.getText()));
        obj.setTipodeproduto((TipoDeProduto)cbTipoProduto.getSelectedItem());

        ProdutosDAO dao = new ProdutosDAO();
        dao.Salvar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoSalvar1ActionPerformed

    private void btnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar1ActionPerformed

        String nameProduct = txtDescricao.getText();

        Produtos obj = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();

        TipoDeProduto tp = new TipoDeProduto();
        TipoDeProdutosDAO tpdao = new TipoDeProdutosDAO();

        obj = dao.BuscarProdutos(nameProduct);

        if(obj.getNameProduct() != null){

            idProduto.setText(String.valueOf(obj.getIdProduct()));
            txtDescricao.setText(obj.getNameProduct());
            txtPreco.setText(String.valueOf(obj.getPrice()));
            txtQuantidade.setText(String.valueOf(obj.getStock()));

            tp = tpdao.BuscarTipoDeProdutos(obj.getTipodeproduto().getProductType());
            cbTipoProduto.getModel().setSelectedItem(tp);

        }else{
            JOptionPane.showMessageDialog(null, "Produto nao encontrado");
        }
    }//GEN-LAST:event_btnPesquisar1ActionPerformed

    private void botaoNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovo1ActionPerformed

        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoNovo1ActionPerformed

    private void botaoEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar1ActionPerformed
        Produtos obj = new Produtos();
        obj.setIdProduct(Integer.valueOf(idProduto.getText()));
        obj.setNameProduct(txtDescricao.getText());
        obj.setPrice(Double.valueOf(txtPreco.getText()));
        obj.setStock(Integer.valueOf(txtQuantidade.getText()));

        TipoDeProduto tp = new TipoDeProduto();
        tp = (TipoDeProduto) cbTipoProduto.getSelectedItem();

        obj.setTipodeproduto(tp);

        ProdutosDAO dao = new ProdutosDAO();
        dao.Editar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoEditar1ActionPerformed

    private void botaoExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluir1ActionPerformed
        Produtos obj = new Produtos();
        obj.setIdProduct(Integer.valueOf(idProduto.getText()));
        ProdutosDAO dao = new ProdutosDAO();
        dao.Excluir(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoExcluir1ActionPerformed

    private void txtPreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreco1ActionPerformed

    private void txtPreco1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreco1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreco1KeyPressed

    private void txtQuantidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidade1ActionPerformed

    private void txtQuantidade1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidade1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidade1KeyPressed

    private void cbTipoProduto1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbTipoProduto1AncestorAdded

    }//GEN-LAST:event_cbTipoProduto1AncestorAdded

    private void cbTipoProduto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoProduto1MouseClicked
        TipoDeProdutosDAO dao = new TipoDeProdutosDAO();
        List<TipoDeProduto> lista = dao.Listar();
        cbTipoProduto.removeAllItems();
        for(TipoDeProduto tp : lista){
            cbTipoProduto.addItem(tp);
        }
    }//GEN-LAST:event_cbTipoProduto1MouseClicked

    private void cbTipoProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoProduto1ActionPerformed

    private void tabela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabela1MouseClicked

    private void idProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProduto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProduto2ActionPerformed

    private void txtDescricao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricao2ActionPerformed

    private void txtDescricao2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricao2KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String nameProduct = txtDescricao.getText();

            Produtos obj = new Produtos();
            ProdutosDAO dao = new ProdutosDAO();

            TipoDeProduto tp = new TipoDeProduto();
            TipoDeProdutosDAO tpdao = new TipoDeProdutosDAO();

            obj = dao.BuscarProdutos(nameProduct);

            if(obj.getNameProduct() != null){

                idProduto.setText(String.valueOf(obj.getIdProduct()));
                txtDescricao.setText(obj.getNameProduct());
                txtPreco.setText(String.valueOf(obj.getPrice()));
                txtQuantidade.setText(String.valueOf(obj.getStock()));

                tp = tpdao.BuscarTipoDeProdutos(obj.getTipodeproduto().getProductType());
                cbTipoProduto.getModel().setSelectedItem(tp);
            }else{
                JOptionPane.showMessageDialog(null, "Produto nao encontrado");
            }
        }
    }//GEN-LAST:event_txtDescricao2KeyPressed

    private void botaoSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvar2ActionPerformed
        Produtos obj = new Produtos();
        obj.setNameProduct(txtDescricao.getText());
        obj.setPrice(Double.valueOf(txtPreco.getText()));
        obj.setStock(Integer.valueOf(txtQuantidade.getText()));
        obj.setTipodeproduto((TipoDeProduto)cbTipoProduto.getSelectedItem());

        ProdutosDAO dao = new ProdutosDAO();
        dao.Salvar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoSalvar2ActionPerformed

    private void btnPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar2ActionPerformed

        String nameProduct = txtDescricao.getText();

        Produtos obj = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();

        TipoDeProduto tp = new TipoDeProduto();
        TipoDeProdutosDAO tpdao = new TipoDeProdutosDAO();

        obj = dao.BuscarProdutos(nameProduct);

        if(obj.getNameProduct() != null){

            idProduto.setText(String.valueOf(obj.getIdProduct()));
            txtDescricao.setText(obj.getNameProduct());
            txtPreco.setText(String.valueOf(obj.getPrice()));
            txtQuantidade.setText(String.valueOf(obj.getStock()));

            tp = tpdao.BuscarTipoDeProdutos(obj.getTipodeproduto().getProductType());
            cbTipoProduto.getModel().setSelectedItem(tp);

        }else{
            JOptionPane.showMessageDialog(null, "Produto nao encontrado");
        }
    }//GEN-LAST:event_btnPesquisar2ActionPerformed

    private void botaoNovo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovo2ActionPerformed

        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoNovo2ActionPerformed

    private void botaoEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar2ActionPerformed
        Produtos obj = new Produtos();
        obj.setIdProduct(Integer.valueOf(idProduto.getText()));
        obj.setNameProduct(txtDescricao.getText());
        obj.setPrice(Double.valueOf(txtPreco.getText()));
        obj.setStock(Integer.valueOf(txtQuantidade.getText()));

        TipoDeProduto tp = new TipoDeProduto();
        tp = (TipoDeProduto) cbTipoProduto.getSelectedItem();

        obj.setTipodeproduto(tp);

        ProdutosDAO dao = new ProdutosDAO();
        dao.Editar(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoEditar2ActionPerformed

    private void botaoExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluir2ActionPerformed
        Produtos obj = new Produtos();
        obj.setIdProduct(Integer.valueOf(idProduto.getText()));
        ProdutosDAO dao = new ProdutosDAO();
        dao.Excluir(obj);
        Utilitarios util = new Utilitarios();
        util.LimpaTela(CadastrarProdutos);
    }//GEN-LAST:event_botaoExcluir2ActionPerformed

    private void txtPreco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreco2ActionPerformed

    private void txtPreco2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreco2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreco2KeyPressed

    private void txtQuantidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidade2ActionPerformed

    private void txtQuantidade2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidade2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidade2KeyPressed

    private void cbTipoProduto2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbTipoProduto2AncestorAdded

    }//GEN-LAST:event_cbTipoProduto2AncestorAdded

    private void cbTipoProduto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoProduto2MouseClicked
        TipoDeProdutosDAO dao = new TipoDeProdutosDAO();
        List<TipoDeProduto> lista = dao.Listar();
        cbTipoProduto.removeAllItems();
        for(TipoDeProduto tp : lista){
            cbTipoProduto.addItem(tp);
        }
    }//GEN-LAST:event_cbTipoProduto2MouseClicked

    private void cbTipoProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoProduto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoProduto2ActionPerformed

    private void tabela2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabela2MouseClicked

    private void txtPesquisaDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaDescricaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaDescricaoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastrarProdutos;
    private javax.swing.JPanel CadastrarProdutos1;
    private javax.swing.JPanel CadastrarProdutos2;
    private javax.swing.JPanel ConsultarProdutos;
    private javax.swing.JPanel PainelControleEstoque;
    private javax.swing.JPanel PainelControleEstoque1;
    private javax.swing.JPanel PainelControleEstoque2;
    public javax.swing.JTabbedPane PainelGuiasMenuControle;
    private javax.swing.JTabbedPane PainelGuiasMenuControle1;
    private javax.swing.JTabbedPane PainelGuiasMenuControle2;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoEditar1;
    private javax.swing.JButton botaoEditar2;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoExcluir1;
    private javax.swing.JButton botaoExcluir2;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoNovo1;
    private javax.swing.JButton botaoNovo2;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoSalvar1;
    private javax.swing.JButton botaoSalvar2;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisar1;
    private javax.swing.JButton btnPesquisar2;
    private javax.swing.JComboBox cbTipoProduto;
    private javax.swing.JComboBox cbTipoProduto1;
    private javax.swing.JComboBox cbTipoProduto2;
    private javax.swing.JTextField idProduto;
    private javax.swing.JTextField idProduto1;
    private javax.swing.JTextField idProduto2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabela1;
    private javax.swing.JTable tabela2;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDescricao1;
    private javax.swing.JTextField txtDescricao2;
    private javax.swing.JTextField txtPesquisaDescricao;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtPreco1;
    private javax.swing.JTextField txtPreco2;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtQuantidade1;
    private javax.swing.JTextField txtQuantidade2;
    // End of variables declaration//GEN-END:variables
}
